### ISSUE TITLE
Values for Ethnicity

### ISSUE THREAD

**Issue by achen01** [haolinnie/Self-Service-Database-UI#10]
Update the ethnicity in the database (currently only three options, hispanic or latino, not hispanic or latino, and declined) to race1 and race 2 that Flori mentioned with more options.

**Comment by haolinnie** [comment]
What's the issue here? The backend schema has been updated to the latest version sent by Flori 
![optho_deid_2020](https://user-images.githubusercontent.com/30088608/74674555-40e61500-5177-11ea-8875-5e4dd9878503.PNG)

**Comment by haolinnie** [comment]
closed
