### ISSUE TITLE
When both eye diagnosis and systemic diagnosis are selected, the table does not show up.

### ISSUE THREAD

**Issue by achen01** [haolinnie/Self-Service-Database-UI#12]
I tried these filters, and the table does not show up, so I think it may have to do with the fact that both eye diagnosis and systemic diagnosis were both selected.

You have selected these filters:
Eye Diagnosis: Central retinal vein occlusion (disorder)
Systemic Diagnosis: Unspecified disorder of skin and subcutaneous tissue_

**Comment by achen01** [comment]
Actually never mind, the reason the table doesn't show up is probably no patient has those filters. Maybe possibly make it so that a message displays "no patient satisfies this criteria" or somethign like that.

**Comment by keremguventurk3123** [comment]
resolved
