### ISSUE TITLE
Patient Images Page

### ISSUE THREAD

**Issue by beatricemakdah** [haolinnie/Self-Service-Database-UI#18]
"Image Procedure" and "Image Laterality" columns are reversed.

**Comment by keremguventurk3123** [comment]
![Screen Shot 2020-02-16 at 5 49 36 PM](https://user-images.githubusercontent.com/44733338/74614300-c10f6a80-50e4-11ea-9f5c-3493b9034aef.png)

this is what I get from the API, can you switch image procedure and laterality?

**Comment by haolinnie** [comment]
Working on it

**Comment by haolinnie** [comment]
What's the exact API call you used to get those results? When I do GET /ssd_api/patient_images?pt_id=20676, I get: 

```
{
	"message": "",
	"result": {
		"20676": [
			{
				"exam_date": "Thu, 09 Aug 2018 00:00:00 GMT",
				"exam_id": 27162,
				"image": {},
				"images": [
					{
						"image_id": 1313149,
						"image_laterality": 2,
						"image_num": 0,
						"image_type": "OD"
					},
					{
						"image_id": 1313150,
						"image_laterality": 32,
						"image_num": 0,
						"image_type": "OS"
					},
					{
						"image_id": 1313151,
						"image_laterality": 2,
						"image_num": 0,
						"image_type": "OS"
					},
					{
						"image_id": 1313152,
						"image_laterality": 2,
						"image_num": 0,
						"image_type": "OD"
					},
					{
						"image_id": 1313157,
						"image_laterality": 21,
						"image_num": 0,
						"image_type": "OD"
					},
					{
						"image_id": 1313158,
						"image_laterality": 21,
						"image_num": 1,
						"image_type": "OD"
					},
					{
						"image_id": 1313153,
						"image_laterality": 2,
						"image_num": 1,
						"image_type": "OD"
					},
					{
						"image_id": 1313154,
						"image_laterality": 2,
						"image_num": 2,
						"image_type": "OD"
					},
					{
						"image_id": 1313155,
						"image_laterality": 2,
						"image_num": 3,
						"image_type": "OD"
					},
					{
						"image_id": 1313156,
						"image_laterality": 2,
						"image_num": 4,
						"image_type": "OD"
					}
				]
			}
		]
	},
	"success": true
}
```

**Comment by keremguventurk3123** [comment]
![Screen Shot 2020-02-16 at 6 50 42 PM](https://user-images.githubusercontent.com/44733338/74615272-4008a100-50ed-11ea-9901-f4b9e0185786.png)

I call apiBaseURL + "/ssd_api/patient_images?pt_id=" + patientID. The patientID is 20676. It's weird that we're getting different results though. 

Also, I think the laterality should be OD and type should be something like "Ir_oct"

**Comment by haolinnie** [comment]
not weird that we're getting different results - my results are from the development branch on my local machine and you are calling the current API deployed on my server which might be buggy.

I'll make sure the newest version has the right results.
