### ISSUE TITLE
Image procedure type in both the patient cohort and patient exams page

### ISSUE THREAD

**Issue by achen01** [haolinnie/Self-Service-Database-UI#19]
Actually, there probably is image procedure type, just currently misplaced listed under image laterality (ir_oct, fundus are image procedure types)

On the patient cohort page, the image procedure type does not show up on the table (example: filter on ir_oct, that column in the table remains empty).

On the exams page, maybe just list image procedure type, or list the important ones that doctors want to see.

**Comment by keremguventurk3123** [comment]
fixed the first one, will leave the other issue for the doctors to decide
