### ISSUE TITLE
Exams Page - exam IDs

### ISSUE THREAD

**Issue by beatricemakdah** [haolinnie/Self-Service-Database-UI#20]
There are many rows in the the exams table that have mysterious exam IDs that are not listed in the database. Where did they come from?

**Comment by keremguventurk3123** [comment]
can you give an example?

**Comment by beatricemakdah** [comment]
![image](https://user-images.githubusercontent.com/57047655/74613917-b7800580-50d8-11ea-9e18-606ce234e5b6.png)

The highlighted ones aren't in the database

**Comment by achen01** [comment]
![image](https://user-images.githubusercontent.com/35311147/74613932-d41c3d80-50d8-11ea-87ef-e26256540087.png)

Here is the corresponding exam for exam ID 12380 in the Excel spreadsheet. There are no exam IDs for 12381, 12382, or 12383.

**Comment by keremguventurk3123** [comment]
![Screen Shot 2020-02-16 at 5 56 50 PM](https://user-images.githubusercontent.com/44733338/74614417-c4efbc80-50e5-11ea-8a3c-130d0768eee9.png)

This is what I get from the API

**Comment by achen01** [comment]
Okay. We just found from the Excel sheet that those exam IDs are from a different table, and those exams don't have images, so maybe it's not a bug. Let's talk about it tomorrow then. Meeting adjourned.

**Comment by haolinnie** [comment]
@keremguventurk3123  What's the API call to reproduce this?

**Comment by achen01** [comment]
the patient images one. baseURL/ssd_api/patient_images

**Comment by keremguventurk3123** [comment]
it's not a bug then. all good!
