### ISSUE TITLE
/ssd_api/filter doesn't work with age - equals

### ISSUE THREAD

**Issue by keremguventurk3123** [haolinnie/Self-Service-Database-UI#21]
![Screen Shot 2020-02-16 at 6 37 04 PM](https://user-images.githubusercontent.com/44733338/74615091-79d8a800-50eb-11ea-9eca-d48d1d9af772.png)

There should be only two patients with age 48 (20676, 64656)

**Comment by haolinnie** [comment]
I thought we decided that 'equal' wasn't used anymore because it's redundant. 
You can achieve 'equal' by setting 'more' and 'less' to be the same value.
Is there a better and cleaner way to implement this? I want to avoid redundancy when possible.

**Comment by keremguventurk3123** [comment]
got it, resolved
